# Docker Compose isolation
COMPOSE_PROJECT_NAME={{APP_ID}}

# Database
DB_USER={{DB_USER}}
DB_PASSWORD={{DB_PASSWORD}}
DB_NAME={{DB_NAME}}

# n8n core
N8N_HOST={{N8N_HOST}}
N8N_PROTOCOL=https
WEBHOOK_URL=https://{{N8N_HOST}}/

# Authentication
N8N_BASIC_AUTH_USER={{N8N_BASIC_AUTH_USER}}
N8N_BASIC_AUTH_PASSWORD={{N8N_BASIC_AUTH_PASSWORD}}

# Encryption
N8N_ENCRYPTION_KEY={{N8N_ENCRYPTION_KEY}}

